.TH "calc_file_len.cpp" 3 "Mon Sep 5 2022" "Version 0" "Onegin foreva" \" -*- nroff -*-
.ad l
.nh
.SH NAME
calc_file_len.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBcalc_file_lines\fP (FILE *src)"
.br
.RI "Calculates amount of lines in a file\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int calc_file_lines (FILE * src)"

.PP
Calculates amount of lines in a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIsrc\fP - FILE* to calculate length of 
.RE
.PP

.PP
Definition at line 7 of file calc_file_len\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin foreva from the source code\&.
