.TH "print_lines.cpp" 3 "Tue Sep 6 2022" "Version 0" "Onegin foreva" \" -*- nroff -*-
.ad l
.nh
.SH NAME
print_lines.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_lines\fP (char **lines, unsigned int line_cnt, FILE *out)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void print_lines (char ** lines, unsigned int line_cnt, FILE * out)"

.PP
.nf
\brief Prints array of c-strings
\param lines - char** type var, that points to the first elem of array
\param line_cnt - amount of strings
\param out - FILE* type var 

.fi
.PP
 This function prints to 'out' file an array of c-strings 
.PP
Definition at line 11 of file print_lines\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin foreva from the source code\&.
