.TH "read_lines.cpp" 3 "Tue Sep 6 2022" "Version 0" "Onegin foreva" \" -*- nroff -*-
.ad l
.nh
.SH NAME
read_lines.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBread_lines\fP (char ***lines, FILE *src, unsigned int line_cnt)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void read_lines (char *** lines, FILE * src, unsigned int line_cnt)"

.PP
.nf
\brief Reads an array of c-strings
\param lines - ptr to a char** that will point to an array of strings
\param src - FILE* to read from
\param line_cnt - max amount of lines read

.fi
.PP
 Reads lines to an array of c-strings reads not more than line_cnt lines may read less and say nothing 
.PP
Definition at line 13 of file read_lines\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin foreva from the source code\&.
