.TH "comps_and_checks.cpp" 3 "Mon Sep 12 2022" "Version 3.01.12" "Onegin forever" \" -*- nroff -*-
.ad l
.nh
.SH NAME
comps_and_checks.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBis_txt\fP (const char c)"
.br
.RI "Checks if c is a letter/number\&. "
.ti -1c
.RI "int \fBcomp_str\fP (const void *line1, const void *line2)"
.br
.ti -1c
.RI "int \fBcomp_arabic\fP (const void *line1, const void *line2)"
.br
.ti -1c
.RI "int \fBcomp_core\fP (\fBline\fP fst, \fBline\fP scd, int delta)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int comp_arabic (const void * line1, const void * line2)"

.PP
.nf
\brief Compares two strings, reverse
\param line1 first line
\param line2 second line
\return -1 if line1 < line2 in reverse
\return 0 if line1 = line2
\return 1 if line1 > line2 in reverse

.fi
.PP
 Compares two strings in reverse Prepares strings for comp_core with delta = -1 
.PP
Definition at line 48 of file comps_and_checks\&.cpp\&.
.SS "int comp_core (\fBline\fP fst, \fBline\fP scd, int delta)"

.PP
.nf
\brief Core of comparison
\param line1 first line
\param line2 second line
\param delta number that is added to lft of each string on each turn
\return -1 - line1 < line2 with current delta
\return 0 - line1 = line2
\return 1 - line1 > line2 with current delta

.fi
.PP
 Compares two strings, where lft points to the beginning of string, rgt - to element next after end of string Uses delta to move ptrs that lets sort strings in reverse 
.PP
Definition at line 83 of file comps_and_checks\&.cpp\&.
.SS "int comp_str (const void * line1, const void * line2)"

.PP
.nf
\brief Compares two strings, straight
\param line1 first line
\param line2 second line
\return -1 if line1 < line2
\return 0 if line1 = line2
\return 1 if line1 > line2

.fi
.PP
 Compares two strings the straight way prepares strings for comp_core with delta = 1 
.PP
Definition at line 28 of file comps_and_checks\&.cpp\&.
.SS "bool is_txt (const char c)"

.PP
Checks if c is a letter/number\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP char to check 
.RE
.PP
\fBReturns\fP
.RS 4
true if is a letter/number 
.PP
false - in any other case 
.RE
.PP

.PP
Definition at line 9 of file comps_and_checks\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin forever from the source code\&.
