.TH "get_len.cpp" 3 "Mon Sep 12 2022" "Version 3.01.12" "Onegin forever" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_len.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBget_len\fP (const char *file_name)"
.br
.RI "Returns len of file in chars\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t get_len (const char * file_name)"

.PP
Returns len of file in chars\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile_name\fP name of file that's length will be returned 
.RE
.PP
\fBReturns\fP
.RS 4
sizeof file in chars 
.RE
.PP

.PP
Definition at line 9 of file get_len\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin forever from the source code\&.
