.TH "line" 3 "Mon Sep 12 2022" "Version 3.01.12" "Onegin forever" \" -*- nroff -*-
.ad l
.nh
.SH NAME
line
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protos\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBlft\fP = NULL"
.br
.ti -1c
.RI "char * \fBrgt\fP = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file protos\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char* line::lft = NULL"

.PP
Definition at line 31 of file protos\&.h\&.
.SS "char* line::rgt = NULL"

.PP
Definition at line 32 of file protos\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin forever from the source code\&.
