.TH "line" 3 "Mon Sep 12 2022" "Version 3.01.12" "Onegin forever" \" -*- nroff -*-
.ad l
.nh
.SH NAME
line
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBlft\fP = NULL"
.br
.ti -1c
.RI "char * \fBrgt\fP = NULL"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin forever from the source code\&.
