.TH "main.cpp" 3 "Mon Sep 12 2022" "Version 3.01.12" "Onegin forever" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBerror_codes\fP \fBerrcod\fP = \fBOK\fP"
.br
.RI "variable to store errors "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
.nf
\brief Contains body of prog

.fi
.PP
 So it's basically what makes it not a set of funcs < Sorts strings pravoslavno
.PP
< Sorts strings arabsky
.PP
Definition at line 12 of file main\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBerror_codes\fP errcod = \fBOK\fP"

.PP
variable to store errors 
.PP
Definition at line 4 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin forever from the source code\&.
