.TH "read_text.cpp" 3 "Mon Sep 12 2022" "Version 3.01.12" "Onegin forever" \" -*- nroff -*-
.ad l
.nh
.SH NAME
read_text.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtext\fP \fBread_text\fP (const char *file_name)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBtext\fP read_text (const char * file_name)"

.PP
.nf
\brief Reads from file_name to text struct
\param file_name name of file to read from
\return struct text variable

.fi
.PP
 In process uses funcs buffer, get_len 
.PP
Definition at line 10 of file read_text\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Onegin forever from the source code\&.
